main: me.RockinChaos.fakecreative.FakeCreative
#${project.version}-b${env.BUILD_NUMBER}
version: 0.0.1-ALPHA
name: FakeCreative
author: RockinChaos
load: POSTWORLD
api-version: 1.13
description: A better creative mode plugin.
website: https://www.spigotmc.org/resources/fakecreative/
softdepend: [BetterNick, PlaceholderAPI, ProtocolLib]

commands:
   gamemode:
      description: Displays a menu giving credit to the author and the help menu command.
      permission: gamemode.use
      aliases: [gamemode]
      usage: |
          /gamemode
          Example: /gamemode
   gm:
      description: Displays a menu giving credit to the author and the help menu command.
      permission: gamemode.use
      aliases: [gm]
      usage: |
          /gm
          Example: /gm
   fakecreative:
      description: Displays a menu giving credit to the author and the help menu command.
      permission: gamemode.use
      aliases: [fakecreative]
      usage: |
          /fakecreative
          Example: /fakecreative
   fc:
      description: Displays a menu giving credit to the author and the help menu command.
      permission: gamemode.use
      aliases: [fc]
      usage: |
          /fc
          Example: /fc