name: Feature Request
description: Suggest a new idea for this resource.
labels: ["Feature Request"]
assignees: RockinChaos
body:
  - type: textarea
    attributes:
      label: Describe The Feature
      description: Is this request related to a problem?
      placeholder: I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Solution
      description: A clear and concise description of what you want to happen.
      placeholder: I would like it when [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I tried modifying the configuration so that [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Any other context or screenshots (highly recommended) about this request.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Checklist
      description: Let's make sure this report is valid.
      options:
        - label: I have read the wiki to make sure my request has not already been implemented.
          required: true
        - label: I ticked all of these boxes without actually reading them.
          required: false
        - label: I have checked that my feature request is unique and another request does not exist.
          required: true